apiVersion: v1
kind: Service
metadata:
  name: cwl-parser-service
spec:
  selector:
    app: cwl-parser
  ports:
  - protocol: "TCP"
    port: 6000
    targetPort: 3000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cwl-parser
spec:
  selector:
    matchLabels:
      app: cwl-parser
  replicas: 4
  template:
    metadata:
      labels:
        app: cwl-parser
    spec:
      containers:
      - name: cwl-parser
        image: cwl_parser:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5002
#      - name: icpcp-planner
#        image: icpcp_planner:latest
#        imagePullPolicy: Never
#        ports:
#          - containerPort: 5001